name = "TwoDG"
uuid = "0ba541ed-3900-48fb-aef1-27df9a57135d"
authors = ["Xin Kai Lee <xin.lee18@imperial.ac.uk> and contributors"]
version = "1.0.0-DEV"

[deps]
DistMesh2D = "f35b52f9-dac7-460d-8eba-9271352c98c8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DistMesh2D = "1.0.0"
LinearAlgebra = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
