name = "TwoDG"
uuid = "0ba541ed-3900-48fb-aef1-27df9a57135d"
authors = ["Xin Kai Lee <xin.lee18@imperial.ac.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
