using DelimitedFiles: readdlm

"""
    make_circle_mesh(size, boundary_refinement) -> (p, t)

Raw unstructured triangulation of the unit circle with element size `size`,
generated by shelling out to Python's distmesh (`pyscripts/`; requires
`python` with `numpy` on the path, distmesh is vendored). Pass
`boundary_refinement = h_boundary` for a mesh graded toward the boundary, or
`nothing` for uniform sizing. Returns vertices `p (np, 2)` and triangles
`t (nt, 3)`; use [`mkmesh_circle`](@ref) for a solver-ready mesh.
"""
function make_circle_mesh(size, boundary_refinement)
    TEMP_DIR = mktempdir()

    if boundary_refinement === nothing
        command = `python pyscripts/make_circle_mesh.py $(size) $(TEMP_DIR)`
    else
        command = `python pyscripts/make_circle_mesh_boundary_refined.py $(size) $(boundary_refinement) $(TEMP_DIR)`
    end

    run(command)

    p = readdlm(joinpath(TEMP_DIR, "p.csv"), ',', Float64)
    t = Int.(readdlm(joinpath(TEMP_DIR, "t.csv"), ',', Float64))

    t .+= 1

    rm(TEMP_DIR, recursive=true, force=true)
    return p, t
end

"""
make_square_mesh 2-d regular triangle mesh generator for the unit square
p, t = squaremesh(m, n, parity)

  p:         node positions (np,2)
  t:         triangle indices (nt,3)
  parity:    flag determining the triangular pattern
              flag = 0 (diagonals sw - ne) (default)
              flag = 1 (diagonals nw - se)
"""
function make_square_mesh(m::Int=10, n::Int=10, parity::Int=0)
    # Generate mesh for unit square
    x = range(0.0, 1.0, length=m)
    y = range(0.0, 1.0, length=n)
    
    # Create meshgrid equivalent in Julia
    X = [x[i] for i in 1:m, _ in 1:n]
    Y = [y[j] for _ in 1:m, j in 1:n]
    
    # Create node positions
    p = hcat(X[:], Y[:])
    
    # Pre-allocate triangle indices
    nt = 2*(m-1)*(n-1)
    t = zeros(Int, nt, 3)
    
    # Generate triangle indices
    idx = 1
    for j in 1:(n-1), i in 1:(m-1)
        i0 = i + (j-1)*m
        i1 = i0 + 1
        i2 = i0 + m
        i3 = i2 + 1
        
        if parity == 0
            t[idx,:] = [i0, i3, i2]
            t[idx+1,:] = [i0, i1, i3]
        else
            t[idx,:] = [i0, i1, i2]
            t[idx+1,:] = [i1, i3, i2]
        end
        
        idx += 2
    end
    
    return p, t
end